feat: status normalisation
ogcio/life-events pull request #112
Opened 2024-04-11 08:34 UTC by nnorbert

Transaction status normalisation

2024-04-11 13:35 UTC, alfonsograziano commented on apps/payments-api/routes/transactions/index.ts
> +          TransactionStatusesEnum.Pending,
Once we do the insert, shouldn't the status be "Initialized"?

2024-04-11 13:36 UTC, alfonsograziano requested changes
As fare as I can see, here has not been updated the manual bank transfer flow with the correct status, right?

2024-04-12 10:58 UTC, nnorbert commented on apps/payments-api/routes/transactions/index.ts
> +          TransactionStatusesEnum.Pending,
However, this part was changed a bit, status is an optional parameter now. If you omit to send status, it will create as Pending by default. OpenBanking and Stripe will have Pending status by default, only Manual transfer use the initiated status. However, it can be changed to insert Initiated by default, and send Pending in case of OB and Stripe.

2024-04-12 11:28 UTC, alfonsograziano approved these changes

2024-04-12 11:30 UTC, merged