chore(documentation): small changes to doc and .env utility script
ogcio/life-events pull request #119
Opened 2024-04-15 14:43 UTC by edge33

This change fixes some minor issues in the docs and adds a utility script

### Ticket:

- No ticket
### Description

- Fixes the doc readme to reference `npm` instead of `yarn`
- Adds a utility script to setup `.env` files based on `.env.sample` for dev setup
## Type

- [ ] **Dependency upgrade**
- [ ] **Bug fix**
- [ ] **New feature**
- [x] **Dev change**

### Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works

2024-04-15 15:18 UTC, GiuliaTeggi commented on package.json
> +    "init-dev": "node scripts/init-env.mjs",
nitpick: this could be renamed to`init-env` or somehow have a reference to the fact it's setting up the `env` files specifically?

2024-04-15 16:37 UTC, SamSalvatico requested changes
Thank you

2024-04-15 16:37 UTC, SamSalvatico commented on package.json
> +    "start": "npm run init-dev && npm run start:docker && concurrently \"npm run start:services\" \"sleep 5 && npm run migrate\"",
Here we should refer to `init-env`

2024-04-15 18:56 UTC, alfonsograziano approved these changes
LGTM

2024-04-16 07:42 UTC, SamSalvatico approved these changes
Great

2024-04-16 07:48 UTC, alfonsograziano approved these changes

2024-04-16 07:57 UTC, merged