Feature: configure logging wrapper
ogcio/life-events pull request #152
Opened 2024-04-23 07:44 UTC by SamSalvatico

### Description

Write a logging wrapper for Fastify that would help us to standardize logs between services as requested in the [API Design document](https://www.notion.so/nearform/APIs-Design-Draft-bc85f57bc75e484ab1de8561f1be2794)

## Type

- [ ] **Dependency upgrade**
- [ ] **Bug fix**
- [x] **New feature**
- [ ] **Dev change**

### Checklist:

**A new PR with the test suite will follow really soon**

2024-04-23 07:54 UTC, alfonsograziano commented on packages/logging-wrapper/package.json
> +    "ts-jest": "^29.1.2",
Usually, we avoid Jest while testing Node.js applications in favour of other test frameworks (like TAP) due to some [known issues](https://github.com/jestjs/jest/issues/2549).

2024-04-23 07:57 UTC, SamSalvatico commented on packages/logging-wrapper/package.json
> +    "ts-jest": "^29.1.2",
Ouch!
I've used that because we have explicit request of do that in our [docs](https://www.notion.so/nearform/APIs-Design-Draft-bc85f57bc75e484ab1de8561f1be2794)

Anyway, thank you, I will update tests and docs!

2024-04-23 07:58 UTC, alfonsograziano commented
@SamSalvatico I like the approach! Would be cool to see some usage examples as well. Can you please add just a basic usage example? Feel free to use the `payments` app :)

2024-04-24 13:00 UTC, GiuliaTeggi commented on packages/logging-wrapper/src/fastify-logging-wrapper.ts
> +    reply.send(buildErrorResponse(error, request));
I wouldn't expect a logging package to also return errors to the client? Is there a way to keep the sending of the response as a responsibility of each api?

2024-04-24 13:29 UTC, SamSalvatico commented on packages/logging-wrapper/src/fastify-logging-wrapper.ts
> +    reply.send(buildErrorResponse(error, request));
Thank you for your thought Giulia

TLDR; I would like to move this behaviour to another shared place, as soon as we have other utils

I agree that the logging-wrapper is not the best place to do it, but I would like to normalize the error handling across all the services to expose a single error format

Anyway, if we need to customize the error response, we can override the error handler easily after the `initializeLoggingHooks` call just invoking
```
app.setErrorHandler(function (error, request, reply) {
    reply.send({ what_we_need: true });
  });
 ```
 
 What do you think about that?

2024-04-24 14:05 UTC, GiuliaTeggi commented on packages/logging-wrapper/src/fastify-logging-wrapper.ts
> +    reply.send(buildErrorResponse(error, request));
Yes I agree on having shared error handling, but couldn't we already setup a shared error-wrapper thing? Why do we need to wait for other utils? :) 

I just feel uneasy about mixing error handling with logging, a separate package would maintain clarity and separation of concerns.

2024-04-24 14:20 UTC, Thurfjell requested changes

2024-04-24 14:20 UTC, Thurfjell commented on packages/logging-wrapper/src/fastify-logging-wrapper.ts
> +    reply.send(buildErrorResponse(error, request));
Absolutely separate concerns. 
Don't make smart things that do multiple things. Let logger log, and only log. Let http handler functions handle the requests.

2024-04-24 14:23 UTC, SamSalvatico commented on packages/logging-wrapper/src/fastify-logging-wrapper.ts
> +    reply.send(buildErrorResponse(error, request));
Okay all, I will create an error-handler PR on top of this PR

2024-04-29 07:06 UTC, SamSalvatico commented
@GiuliaTeggi @Thurfjell I've merged previous PRs on this, splitting concerns between `logging-wrapper` and `error-handler`

2024-04-29 08:50 UTC, GiuliaTeggi approved these changes

2024-04-29 13:16 UTC, SamSalvatico reviewed
Readded

2024-04-30 07:33 UTC, merged