Message scheduler
ogcio/life-events pull request #205
Opened 2024-05-06 13:59 UTC by Thurfjell

### Ticket:

- [XXX](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/XXX)

### Description

Please include a summary of the changes and the related issue.

## Type

- [ ] **Dependency upgrade**
- [ ] **Bug fix**
- [ ] **New feature**
- [ ] **Dev change**

### Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works

### Screenshots:

N/A

2024-05-13 12:30 UTC, Thurfjell commented on apps/messaging-api/routes/messages/index.ts
> +  // A job is tied to one user. We dont need any magic
Just context before deleting this comment. This function used to handle all users for the base template reference.

2024-05-13 14:29 UTC, SamSalvatico reviewed
Please merge `dev` on this, on starting I have some problems that have been fixed on dev

2024-05-13 14:29 UTC, SamSalvatico commented on package.json
>      "init": "npm run init:packages && npm run init:env && npm run init:ds && npm run stop:logto && npm run init:logto",
Please update init like this
```
"build:docker": "docker build -t base-deps:latest  --file Dockerfile . && docker build -t design-system-container:latest --file packages/design-system/Dockerfile .",
 "init": "npm run init:packages && npm run init:env && npm run init:ds && npm run stop:logto && npm run init:logto && npm run build:docker",
 ```
   Because otherwise, if you don't have base images, the docker compose fails, now that scheduler api is added

2024-05-13 14:29 UTC, SamSalvatico commented on docker-compose.yaml
> +    build: './apps/scheduler-api'
Please update build with this to maintain the context at the root folder

```
scheduler:
    image: scheduler-api-container:latest
    build:
      context: .
      dockerfile: ./apps/scheduler-api/Dockerfile

2024-05-13 14:29 UTC, SamSalvatico commented on docker-compose.yaml
> +      - 8004:8004
you can't expose 5 replicas on the same port

2024-05-13 14:29 UTC, SamSalvatico commented on apps/scheduler-api/app.ts
> +import { STATUS_CODES } from "http";
unused

2024-05-13 16:05 UTC, SamSalvatico commented on apps/messaging-api/routes/messages/index.ts
> +        error = await scheduledTemplate(app.pg.pool, job.jobId, job.userId);
No try catch in scheduled template, then if an unhandled exception is thrown the job will be stuck

2024-05-17 05:24 UTC, SamSalvatico requested changes
Thank you, @Thurfjell

2024-05-17 05:24 UTC, SamSalvatico commented on docker-compose.yaml
> +      - './apps/scheduler-api/.env'
It won't work
In the `.env` file of the `scheduler` package you expect DB keys with `_SCHEDULER_` in their name, but in the `scheduler-api` they are different.
Please directly use environment variables in the docker compose file like
```
environment:
      POSTGRES_SCHEDULER_USER: postgres
      POSTGRES_SCHEDULER_PASSWORD: postgres
      POSTGRES_SCHEDULER_HOST: postgresql
      POSTGRES_SCHEDULER_PORT: 5432
      POSTGRES_SCHEDULER_DB_NAME: scheduler

``` 
In this way I've been able to make it work, or add a dedicated `.env.docker` file so to make the original one independent by the run on docker

2024-05-17 12:15 UTC, williamwd approved these changes

2024-05-17 12:15 UTC, merged