API pagination - transactions
ogcio/life-events pull request #261
Opened 2024-05-16 08:35 UTC by nnorbert

API pagination - transactions

2024-05-16 09:40 UTC, SamSalvatico requested changes
Thank you for taking care of it, @nnorbert

2024-05-16 09:40 UTC, SamSalvatico commented on apps/payments-api/routes/schemas/index.ts
> +  next: PaginationLink,
`next` and `prev` are optional
e.g. `self` is the last or the first page

2024-05-16 09:40 UTC, SamSalvatico commented on apps/payments-api/routes/transactions/index.ts
> +      const { offset = 0, limit = 10 } = request.query;
setting default values in type declaration you can avoid to set them here

2024-05-16 09:40 UTC, SamSalvatico commented on apps/payments-api/routes/transactions/index.ts
> +        totalCountResult = await app.pg.query(
please try to reuse the shared part of the query between the two queries to avoid to update only one of them missing the other one in future

(the FROM and the JOINS are shared between them)

2024-05-16 09:40 UTC, SamSalvatico commented on apps/payments-api/routes/transactions/index.ts
> +          "X-Total-Count": totalCount,
I think we should add the total count in the response body as metadata instead of having it in headers, to have a common way to expose data

2024-05-16 09:40 UTC, SamSalvatico commented on apps/payments/app/[locale]/(hosted)/paymentSetup/page.tsx
> +    offset: pageToOffset(page ?? 1, limit ?? 10),
we should set the default limit and offset in a files that export shared constants

2024-05-16 09:40 UTC, SamSalvatico commented on apps/payments/messages/en.json
> +    "previous": "Previous",
Would we like to also expose `first` and `last`?

2024-05-17 08:31 UTC, nnorbert commented on apps/payments-api/routes/schemas/index.ts
> +  offset: Type.Optional(Type.Number()),
Done

2024-05-17 08:36 UTC, nnorbert commented on apps/payments-api/routes/schemas/index.ts
> +  next: PaginationLink,
Done

2024-05-17 08:41 UTC, nnorbert commented on apps/payments-api/routes/schemas/index.ts
> +    metadata: Type.Object({
Done

2024-05-17 08:42 UTC, nnorbert commented on apps/payments-api/routes/transactions/index.ts
> +      const { offset = 0, limit = 10 } = request.query;
Done

2024-05-17 08:50 UTC, nnorbert commented on apps/payments-api/routes/transactions/index.ts
> +        totalCountResult = await app.pg.query(
Done

2024-05-17 08:53 UTC, nnorbert commented on apps/payments-api/routes/transactions/index.ts
> +          "X-Total-Count": totalCount,
Done.

2024-05-17 08:57 UTC, nnorbert commented on apps/payments/app/[locale]/(hosted)/paymentSetup/page.tsx
> +    offset: pageToOffset(page ?? 1, limit ?? 10),
Done, moved into the utils.ts level.

2024-05-17 09:00 UTC, nnorbert commented on apps/payments/messages/en.json
> +    "previous": "Previous",
I won't show Fisrt/Last on the ui in a text form. There will be page numbers, 1 and N, so I think we don't need this at this moment.

2024-05-17 12:37 UTC, SamSalvatico approved these changes
LGTM

2024-05-17 13:10 UTC, SamSalvatico approved these changes

2024-05-20 08:18 UTC, merged