Analytics integration
ogcio/life-events pull request #621
Opened 2024-06-18 14:42 UTC by nnorbert

Analytics integration

2024-06-18 21:00 UTC, alfonsograziano commented on apps/home/.env.sample
> +NEXT_PUBLIC_MATOMO_URL=
Shouldn't we add here an example of string here?

2024-06-18 21:01 UTC, alfonsograziano commented on apps/home/.env.sample
> +NEXT_PUBLIC_MATOMO_URL=
Since we need this variable: NEXT_PUBLIC_MATOMO_URL, do we need to change the Dockerfile and the other files to add the variables at build time? Otherwise the pipeline will fail

2024-06-19 07:58 UTC, nnorbert commented on apps/home/.env.sample
> +NEXT_PUBLIC_MATOMO_URL=
Done

2024-06-19 08:01 UTC, nnorbert commented on apps/home/.env.sample
> +NEXT_PUBLIC_MATOMO_URL=
Done. Terraform is also updated https://github.com/ogcio/life-events-terraform/pull/30

2024-06-19 09:04 UTC, alfonsograziano commented on pipeline-variables/dev.yml
> +  nextPublicBuildingBlocksMatomoSiteId: 14
Do we want to have a single SiteId for all the Building Blocks? @andreacappadona17 this is more a question on the business side of things I think :)

2024-06-19 09:13 UTC, alfonsograziano commented on apps/home/Dockerfile
> +ENV NEXT_PUBLIC_MATOMO_SITE_ID=$NEXT_PUBLIC_BUILDING_BLOCKS_MATOMO_SITE_ID
I like this solution, makes sense :)

2024-06-19 09:14 UTC, alfonsograziano approved these changes
LGTM - @nnorbert shall we add some documentation as well to explain other devs how to integrate Matomo in their applications?

2024-06-19 09:17 UTC, andreacappadona17 commented on pipeline-variables/dev.yml
> +  nextPublicBuildingBlocksMatomoSiteId: 14
We'd rather have multiple siteIds, as it's possible to get aggregates of multiple sites by using roll-up reporting, while splitting metrics based on the url or source would be harder if we use the same website.
In terms of permissions, there could be a "payments analytics" permission that would be mapped to the single siteId.

2024-06-19 09:18 UTC, andreacappadona17 commented
LGTM!

2024-06-19 09:19 UTC, andreacappadona17 approved these changes

2024-06-25 08:06 UTC, andreacappadona17 requested changes

2024-06-25 08:06 UTC, andreacappadona17 commented on documentation/docs/analytics.md
> +- **customDimensions**: It is a custom attribute; we can have as many dimensions as we want. However, the current limit is 40 (dimension1 - dimension40). These attributes describe specific characteri
```suggestion
- **customDimensions**: It is a custom attribute; we can have as many dimensions as we want. However, the current limit is 40 (dimension1 - dimension40). These attributes describe specific characteristics within your Matomo table report. Typically, dimensions are displayed in the first column of the report and provide context to the metrics. Dimensions must be configured on Matomo by admins before using them in the code.
```

2024-06-25 08:30 UTC, andreacappadona17 approved these changes

2024-06-25 08:30 UTC, merged