chore(docker): add script with scheduler
ogcio/life-events pull request #641
Opened 2024-06-24 13:48 UTC by SamSalvatico

### Description

To speed up common startup of the service, removed the scheduler from the normal start script
## Type

- [ ] **Dependency upgrade**
- [ ] **Bug fix**
- [ ] **New feature**
- [x] **Dev change**

2024-06-24 16:21 UTC, Thurfjell commented
I mean anything relying on scheduling wont work if you `run npm start ` now. Is there no way of caching/speeding up the image? (always is isn't it). This will break the "one script to run app".

2024-06-24 16:22 UTC, Thurfjell requested changes
Let's discuss implications.

2024-06-25 07:57 UTC, SamSalvatico commented
> I mean anything relying on scheduling wont work if you `run npm start ` now. Is there no way of caching/speeding up the image? (always is isn't it). This will break the "one script to run app".

Probably you're right, I will make the default script also run scheduler and create one with no scheduler

2024-06-25 08:49 UTC, Thurfjell approved these changes

2024-06-25 08:55 UTC, merged