Allow payment method choice within an iframe
ogcio/life-events pull request #76
Opened 2024-04-02 17:56 UTC by alfonsograziano

### Description

By changing the payment method selection from a series of links to a form with multiple radio buttons, I accidentally broke the iframe flow due to a missing parent redirect. This fixes the issue

## Type

- [ ] **Dependency upgrade**
- [X] **Bug fix**
- [ ] **New feature**
- [ ] **Dev change**

2024-04-02 18:01 UTC, alfonsograziano commented on azure_pipelines.yml
> +    default:
Sorry for all the changes here, must be the prettier plugin with the format on save

2024-04-03 06:41 UTC, SamSalvatico requested changes

2024-04-03 06:41 UTC, SamSalvatico commented on azure_pipelines.yml
> -            arguments: '--build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$(nextPublicStripePublishableKey)'
You have to set `NEXT_PUBLIC_HOST_URL` also here if you need to use it in the Dockerfile

2024-04-03 06:41 UTC, SamSalvatico commented on pipeline-variables/dev.yml
> +  nextPublicHostUrl: http://payments.dev.blocks.gov.ie
In the .env file you've set a trailing slash at the end of the URL, just ensure that it would work also without it (or just add it here too 😁 )

2024-04-03 07:58 UTC, alfonsograziano commented on azure_pipelines.yml
> -            arguments: '--build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$(nextPublicStripePublishableKey)'
Fixed, thanks!

2024-04-03 07:58 UTC, alfonsograziano commented on pipeline-variables/dev.yml
> +  nextPublicHostUrl: http://payments.dev.blocks.gov.ie
Good catch, to keep it consistent I added the slask

2024-04-03 08:23 UTC, SamSalvatico approved these changes
LGTM

2024-04-03 10:39 UTC, williamwd commented on azure_pipelines.yml
> +    default:
No problem. I'll revert some things just so it stays consistent with the Azure documentation.

2024-04-03 12:42 UTC, merged